- src/index.ts
fix FunctionsClient constructor
FunctionsClient constructor requires to pass `{}` as options if you don't want to pass headers or fetch
Add `options` default value `{}` in FunctionsClient constructor
> fix: FunctionsClient constructor default options

- src/FunctionsClient.ts
since they don't exist in Node
> fix: guard Blob and FormData

- src/FunctionsClient.ts
and if the user hasn't passed in a content-type header via the constructor arguments
before we set application/json as the content type even if there are no function args set
> add content type headers only if func args are set

- src/FunctionsClient.ts
- src/types.ts
what we had in v1 was good. Having an object to pass in is better cos all arguments except function name we have are optional.
Also making invoke a generic type function so that you can type the value returned by your function
> fix: revert invoke function signature

- .github/workflows/docs.yml
- .github/workflows/tests.yml
This PR updates GitHub actions to add a new Test workflow and also changes node version to 18 (next LTS from Oct 2022). Going with node 18 prevents us from having to polyfills for tests.
Current workflows use Node 16 and doesn't have a test workflow.
New test workflow will run on every PR and pushes to branchs `main` and `rc`.
NA
> Update GitHub Actions

- test/relay/container.ts
- test/spec/hello.spec.ts
- update deno-relay to v1.5.0 in tests
- update functions invocation test with methods other than post as it is now allowed
> update deno-relay to v1.5.0

- src/FunctionsClient.ts
- src/types.ts
It's a feature that adds support for different HTTP verbs in invoking functions. Edge functions now support different HTTP verbs (such as GET, PUT and DELETE) however the functions-js library didn't get updated to let users do that.
Edge functions now support different HTTP verbs (such as GET, PUT and DELETE) however the functions-js library didn't get updated to let users do that.
This is related to [this discussion](https://github.com/supabase/supabase/discussions/11753)
It keeps the default behaviour of calling with POST, however lets users to choose a different HTTP verb if they needed to. It is legacy compliant so using this new version doesn't break any legacy/existing code.
none at the moment
> added support for different HTTP verbs in invoking functions

- src/types.ts
Bug fix
#56
Fix errors related to the incorrect setup of FunctionsError class.
Fixes this:
```sh
./node_modules/@supabase/functions-js/src/types.ts:21:11
Type error: Only public and protected base class methods are accessible via the 'super' keyword.
19 |   constructor(message: string, name = 'FunctionsError', context?: any) {
20 |     super(message)
> 21 |     super.name = name
|           ^
22 |     this.context = context
23 |   }
24 | }
```
> Fix `FunctionsError` class constructor

- package-lock.json
- package.json
- src/helper.ts
- src/types.ts
- test/functions/hijack/index.ts
- test/relay/container.ts
- test/utils/fetch.ts
Part of fixing https://github.com/supabase/supabase-js/issues/612
> fix: use @supabase/node-fetch

- src/FunctionsClient.ts
- src/types.ts
- test/spec/params.spec.ts
Improve DX for regional Edge Function invocation. 
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> Feat add regional options

- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- README.md
Bump CI/CD versions (there were warnings about node 18 being deprecated):
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> fix: bump ci/cd version

- src/index.ts
I need to trigger a semantic release to get the type exported.
Unblocks: https://github.com/supabase/supabase-js/pull/964
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
> fix: trigger semantic release & export type FunctionRegion

- src/FunctionsClient.ts
Feature/bug fix: Passing through event streams so that OpenAI completions, etc. can be proxied
Event streams are concatenated and only returned at the end of the stream.
Please link any relevant issues here.
Event streams are directly passed so that they can be used properly.
Anything I should change elsewhere, like documentation?
> Directly pass through event streams

- src/edge-runtime.d.ts
This PR adds a type definition file which can be imported into edge functions to get Edge Runtime specific global types.
Then in an edge function these types can be added as:
```
/// <reference types="npm:https://esm.sh/@supabase/functions-js/src/edge-runtime.d.ts" />
```
> feat: add Edge Runtime global types

- .github/workflows/release.yml
- .releaserc.json
- jsr.json
- package-lock.json
- package.json
- src/index.ts
- src/types.ts
- test/spec/params.spec.ts
- tsconfig.json
> feat: configure to publish to JSR

- .github/workflows/release.yml
Job needs write permissions to be able to create release: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
> fix: jsr publish write permissions.

- .github/workflows/release.yml
semantic-release adds a comment to issues, need to allow this in the release action.
> fix: allow wirting to issues.

- src/edge-runtime.d.ts
Bug fix
Adds typing for `EdgeRuntime.waitUntil` to edge-runtime.d.ts.
> fix: add a type for `EdgeRuntime.waitUntil`

- jest.config.ts
Type definition files (.d.ts files) should not be included in coverage calculations. They are TypeScript declaration files that only contain type information and are removed during compilation to JavaScript. Including in the coverage reportartificially lowers the overall metric
> Ignore type definitions in coverage metrics

- src/FunctionsClient.ts
- src/types.ts
- test/spec/hello.spec.ts
- Updated invoke method to include response object in both success and error cases
- Added test cases to verify response object is present in function invocations
- Ensures compliance with FunctionsResponse type definition
Fixes #65 . Supersedes #98
> fix: include response object in FunctionsClient invoke method return

- .github/workflows/preview-release.yml
- README.md
Infrastructure improvement - adds a preview release workflow for easier testing of changes.
Contributors and maintainers need to manually build and test changes locally or wait for official releases to test package changes.
- Adds automated preview release workflow using [`pkg.pr.new`](https://github.com/stackblitz-labs/pkg.pr.new)
- Triggers on pushes to `master` branch and PRs with the `trigger: preview` label
- Automatically publishes preview packages that can be installed and tested
- Provides temporary package URLs for quick testing without affecting the main package
This workflow allows for:
- Quick testing of PR changes before merging
- Easy collaboration on features by sharing preview package links
- Reduced friction in the development and review process
The workflow uses the …
> chore: add preview release

- package-lock.json
- package.json
Update typedoc to `0.23.28`. This is needed in the monorepo, due to hoisting issues.
> fix: update typedoc to 0.23
